package com.wms.business;

import com.plat.common.beans.BaseModel;

// Generated 2017-3-23 11:13:15 by Hibernate Tools 5.2.1.Final

/**
 * WmsAdj generated by hbm2java
 */
public class WmsAdj extends BaseModel {
	private static final long serialVersionUID = 1L;
	private String adjCode;
	private String adjTime;
	private String adjReason;
	private String gcode;
	private String gtype;
	private String boxCode;
	private String storageCode;
	private Integer goalNum;
	private Integer usedNum;
	private Integer adjNum;
	private String batchCode;
	private String traceCode;
	private Integer statu;
	private String oraCode;
	private String whCode;
	private Integer lockStock;
	private Integer type;

	public String getAdjCode() {
		return adjCode;
	}

	public void setAdjCode(String adjCode) {
		this.adjCode = adjCode;
	}

	public String getAdjTime() {
		return adjTime;
	}

	public void setAdjTime(String adjTime) {
		this.adjTime = adjTime;
	}

	public String getAdjReason() {
		return adjReason;
	}

	public void setAdjReason(String adjReason) {
		this.adjReason = adjReason;
	}

	public String getGcode() {
		return gcode;
	}

	public void setGcode(String gcode) {
		this.gcode = gcode;
	}

	public String getGtype() {
		return gtype;
	}

	public void setGtype(String gtype) {
		this.gtype = gtype;
	}

	public String getBoxCode() {
		return boxCode;
	}

	public void setBoxCode(String boxCode) {
		this.boxCode = boxCode;
	}

	public String getStorageCode() {
		return storageCode;
	}

	public void setStorageCode(String storageCode) {
		this.storageCode = storageCode;
	}

	public Integer getGoalNum() {
		return goalNum;
	}

	public void setGoalNum(Integer goalNum) {
		this.goalNum = goalNum;
	}

	public Integer getUsedNum() {
		return usedNum;
	}

	public void setUsedNum(Integer usedNum) {
		this.usedNum = usedNum;
	}

	public Integer getAdjNum() {
		return adjNum;
	}

	public void setAdjNum(Integer adjNum) {
		this.adjNum = adjNum;
	}

	public String getBatchCode() {
		return batchCode;
	}

	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}

	public String getTraceCode() {
		return traceCode;
	}

	public void setTraceCode(String traceCode) {
		this.traceCode = traceCode;
	}

	public Integer getStatu() {
		return statu;
	}

	public void setStatu(Integer statu) {
		this.statu = statu;
	}

	public String getOraCode() {
		return oraCode;
	}

	public void setOraCode(String oraCode) {
		this.oraCode = oraCode;
	}

	public String getWhCode() {
		return whCode;
	}

	public void setWhCode(String whCode) {
		this.whCode = whCode;
	}

	public Integer getLockStock() {
		return lockStock;
	}

	public void setLockStock(Integer lockStock) {
		this.lockStock = lockStock;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
